### ISSUE TITLE
Non-UTF-8 code starting with '\xe8'

### ISSUE THREAD

**Issue by nicinuse** [T-Systems-MMS/check_kubernetes#1]
Hi there,
running the scripts on a docker container (alpine:latest) throws the following error:

`
python3 check_pods
File "check_pods", line 1
SyntaxError: Non-UTF-8 code starting with '\xe8' in file check_pods on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`

**Comment by neubi4** [comment]
Hey,

since the files are already UTF-8, i only added the utf-8 encoding header in branch fix/utf-8.

Could you please test if this fixes your error?

**Comment by nicinuse** [comment]
Hi there,
sadly that does not fix the issue. Maybe it's related to alpine and not to your script.
Thanks so far, i'll investigate further.

**Comment by nicinuse** [comment]
Hi again,
if using python 2.7, the error is benarly the same
`File "/usr/lib/nagios/plugins/check_pods", line 1
SyntaxError: Non-ASCII character '\xe8' in file /usr/lib/nagios/plugins/check_pods on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

The problem(s) persists even if using the official python:*-alpine images.

kind regards

**Comment by schurzi** [comment]
Hey @nicinuse,
now I had some time to look into this. And I think I found the problem. You are trying to call the compiled executable with python.
So instead of this: 
`python .../check_pods`

Please try either of these (depending on if you use the downloaded release or the source python file from the repository):
```
.../check_pods
python .../check_pods.py
```
